version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
    labels:
      - "a:chore"
      - "in:build"
      - "in:dependencies"
    groups:
      "@actions/artifacts":
        patterns:
          - "actions/deploy-pages"
          - "actions/download-artifact"
          - "actions/upload-artifact"
          - "actions/upload-pages-artifact"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    labels:
      - "a:chore"
      - "in:dependencies"